export const defaultVocab = [
  {id:1,word:"Tolerance",phonetic:"/ˈtɒl.ər.əns/",cat:"general",group:"GD&T Basics",def:"The allowed amount of error or variation from the perfect measurement.",ex:"Diameter 20mm with tolerance ±0.05mm.",sentence:"Tolerance values on every dimension."},
  {id:2,word:"Feature",phonetic:"/ˈfiː.tʃər/",cat:"general",group:"GD&T Basics",def:"Any physical part that can be measured — hole, surface, slot, boss.",ex:"Bolt features: head, thread, shank.",sentence:"Inspector measured every feature."},
  {id:3,word:"Nominal Size",phonetic:"/ˈnɒm.ɪ.nəl saɪz/",cat:"general",group:"GD&T Basics",def:"The perfect, ideal size as designed.",ex:"Nominal 25mm, real 24.97mm.",sentence:"Nominal size of shaft is 30mm."},
  {id:4,word:"Actual Size",phonetic:"/ˈæk.tʃu.əl saɪz/",cat:"general",group:"GD&T Basics",def:"The real measured size after manufacturing.",ex:"Measured 49.97mm = actual size.",sentence:"Measured actual size of each hole."},
  {id:5,word:"Inspection",phonetic:"/ɪnˈspek.ʃən/",cat:"general",group:"GD&T Basics",def:"Measuring and checking a part meets requirements.",ex:"CMM machine measures features.",sentence:"Parts pass final inspection."},
  {id:6,word:"Callout",phonetic:"/ˈkɔːl.aʊt/",cat:"general",group:"GD&T Basics",def:"Note or symbol on drawing giving instructions.",ex:"M12×1.5 — 6H is a callout.",sentence:"GD&T callout for hole position."},
  {id:7,word:"Assembly",phonetic:"/əˈsem.bli/",cat:"general",group:"GD&T Basics",def:"Parts connected to make a product.",ex:"Engine = assembly of hundreds of parts.",sentence:"Bolt holes align during assembly."},
  {id:8,word:"Specification",phonetic:"/ˌspes.ɪ.fɪˈkeɪ.ʃən/",cat:"general",group:"GD&T Basics",def:"Detailed requirement for a part.",ex:"Diameter 20mm ±0.01, 28-32 HRC.",sentence:"Failed surface finish specification."},
  {id:9,word:"Deviation",phonetic:"/ˌdiː.viˈeɪ.ʃən/",cat:"general",group:"GD&T Basics",def:"Difference between actual and nominal.",ex:"100mm actual 100.03 = +0.03 deviation.",sentence:"Deviation within tolerance."},
  {id:10,word:"Mating Surface",phonetic:"/ˈmeɪ.tɪŋ ˈsɜː.fɪs/",cat:"general",group:"GD&T Basics",def:"Surface touching another part in assembly.",ex:"Flange face bolting to another.",sentence:"Flatness 0.02mm on mating surface."},
  {id:11,word:"Upper Deviation",phonetic:"/ˈʌp.ər/",cat:"tolerance",group:"GD&T Basics",def:"Max size ABOVE nominal.",ex:"+0.05mm upper deviation.",sentence:"Max 0.05mm larger."},
  {id:12,word:"Lower Deviation",phonetic:"/ˈləʊ.ər/",cat:"tolerance",group:"GD&T Basics",def:"Max size BELOW nominal.",ex:"-0.05mm lower deviation.",sentence:"Min size = nominal - 0.1mm."},
  {id:13,word:"Bilateral Tolerance",phonetic:"/baɪˈlæt.ər.əl/",cat:"tolerance",group:"GD&T Basics",def:"Error allowed in BOTH directions.",ex:"25 ±0.05mm.",sentence:"Bilateral ±0.1mm."},
  {id:14,word:"Unilateral Tolerance",phonetic:"/ˌjuː.nɪˈlæt.ər.əl/",cat:"tolerance",group:"GD&T Basics",def:"Error in ONE direction only.",ex:"25 +0.0/-0.1.",sentence:"Shaft always fits."},
  {id:15,word:"Tolerance Zone",phonetic:"/zəʊn/",cat:"tolerance",group:"GD&T Basics",def:"Area where feature must lie.",ex:"⌀0.5mm cylindrical zone.",sentence:"Inside tolerance zone."},
  {id:16,word:"MMC",phonetic:"/ɛm.ɛm.siː/",cat:"tolerance",group:"GD&T Basics",def:"Maximum Material Condition.",ex:"Shaft MMC = 20.1mm.",sentence:"Extra tolerance at MMC."},
  {id:17,word:"LMC",phonetic:"/ɛl.ɛm.siː/",cat:"tolerance",group:"GD&T Basics",def:"Least Material Condition.",ex:"Shaft LMC = 19.9mm.",sentence:"Min wall thickness at LMC."},
  {id:18,word:"RFS",phonetic:"/ɑːr.ɛf.ɛs/",cat:"tolerance",group:"GD&T Basics",def:"Regardless of Feature Size.",ex:"No modifier = RFS.",sentence:"0.1mm at every size."},
  {id:19,word:"Bonus Tolerance",phonetic:"/ˈbəʊ.nəs/",cat:"tolerance",group:"GD&T Basics",def:"Extra tolerance from MMC departure.",ex:"Bonus = Actual - MMC.",sentence:"Received bonus tolerance."},
  {id:20,word:"Tolerance Stack-up",phonetic:"/stæk ʌp/",cat:"tolerance",group:"GD&T Basics",def:"Multiple tolerances adding up.",ex:"±0.1 + ±0.15 = 0.25mm.",sentence:"Stack-up verified assembly."},
  {id:21,word:"Virtual Condition",phonetic:"/ˈvɜː.tʃu.əl/",cat:"tolerance",group:"GD&T Basics",def:"Worst boundary (size + geo tol).",ex:"⌀20 + 0.1 = 20.1mm VC.",sentence:"Gauge based on VC."},
  {id:22,word:"Fit",phonetic:"/fɪt/",cat:"tolerance",group:"GD&T Basics",def:"Shaft-hole relationship.",ex:"⌀20.0 in ⌀20.1 = Clearance.",sentence:"Clearance fit for rotation."},
  {id:23,word:"Datum",phonetic:"/ˈdeɪ.təm/",cat:"datum",group:"GD&T Basics",def:"Perfect reference for measurements.",ex:"Datum A = bottom face.",sentence:"Surface plate = Datum A."},
  {id:24,word:"Datum Feature",phonetic:"/ˈfiː.tʃər/",cat:"datum",group:"GD&T Basics",def:"Real physical surface = datum.",ex:"Actual bottom face.",sentence:"Must be clean."},
  {id:25,word:"Datum Reference Frame",phonetic:"/freɪm/",cat:"datum",group:"GD&T Basics",def:"3D coordinate system from datums.",ex:"A=XY, B=YZ, C=XZ.",sentence:"CMM uses DRF."},
  {id:26,word:"Primary Datum",phonetic:"/ˈpraɪ.mɛr.i/",cat:"datum",group:"GD&T Basics",def:"First datum, 3 contact points.",ex:"Block on table.",sentence:"Flange as primary."},
  {id:27,word:"Secondary Datum",phonetic:"/ˈsek.ən.dɛr.i/",cat:"datum",group:"GD&T Basics",def:"Second datum, 2 points.",ex:"Against wall.",sentence:"Bore as secondary."},
  {id:28,word:"Tertiary Datum",phonetic:"/ˈtɜː.ʃər.i/",cat:"datum",group:"GD&T Basics",def:"Third datum, 1 point.",ex:"Corner pin.",sentence:"Hole as tertiary."},
  {id:29,word:"Degree of Freedom",phonetic:"/dɪˈɡriː/",cat:"datum",group:"GD&T Basics",def:"One way object can move. 6 total.",ex:"Coin: 3 DOF on table.",sentence:"Datums remove DOF."},
  {id:30,word:"3-2-1 Rule",phonetic:"/θriː tuː wʌn/",cat:"datum",group:"GD&T Basics",def:"3+2+1 = 6 DOF removed.",ex:"Table + Wall + Pin.",sentence:"Fixture uses 3-2-1."},
  {id:31,word:"True Position",phonetic:"/pəˈzɪʃ.ən/",cat:"symbol",group:"GD&T Basics",def:"GD&T (⊕) exact location.",ex:"⌀0.5mm from datums.",sentence:"All bolt holes."},
  {id:32,word:"Flatness",phonetic:"/ˈflæt.nəs/",cat:"symbol",group:"GD&T Basics",def:"Surface flatness (⏥).",ex:"0.02mm flatness.",sentence:"Sealing face."},
  {id:33,word:"Circularity",phonetic:"/ˌsɜː.kjʊˈlær/",cat:"symbol",group:"GD&T Basics",def:"Cross-section roundness (○).",ex:"0.03mm circularity.",sentence:"Bearing journal."},
  {id:34,word:"Cylindricity",phonetic:"/ˌsɪl.ɪnˈdrɪs/",cat:"symbol",group:"GD&T Basics",def:"Roundness + straightness (⌭).",ex:"0.05mm cylindricity.",sentence:"Prevents leakage."},
  {id:35,word:"Parallelism",phonetic:"/pəˈræl/",cat:"symbol",group:"GD&T Basics",def:"Parallel to datum (∥).",ex:"0.05mm to Datum A.",sentence:"Top to bottom."},
  {id:36,word:"Perpendicularity",phonetic:"/pəˌpen.dɪˈkjuː/",cat:"symbol",group:"GD&T Basics",def:"90° to datum (⊥).",ex:"⌀0.08mm.",sentence:"Column to base."},
  {id:37,word:"Angularity",phonetic:"/ˌæŋ.ɡjʊˈlær/",cat:"symbol",group:"GD&T Basics",def:"Specific angle (∠).",ex:"45° angularity 0.1mm.",sentence:"Chamfer 0.2mm."},
  {id:38,word:"Runout",phonetic:"/ˈrʌn.aʊt/",cat:"symbol",group:"GD&T Basics",def:"Wobble during rotation.",ex:"0.1mm runout.",sentence:"Prevents vibration."},
  {id:39,word:"Profile",phonetic:"/ˈprəʊ.faɪl/",cat:"symbol",group:"GD&T Basics",def:"3D curved shape (⌓).",ex:"Within 0.5mm of CAD.",sentence:"Blade profile ±0.15mm."},
  {id:40,word:"Concentricity",phonetic:"/ˌkɒn.sənˈtrɪs/",cat:"symbol",group:"GD&T Basics",def:"Shared center axis (◎).",ex:"0.05mm concentricity.",sentence:"Drum concentricity."},
  {id:41,word:"CMM",phonetic:"/siː.ɛm.ɛm/",cat:"measurement",group:"GD&T Basics",def:"Coordinate Measuring Machine.",ex:"Measures X,Y,Z.",sentence:"Inspected holes."},
  {id:42,word:"Micrometer",phonetic:"/maɪˈkrɒm/",cat:"measurement",group:"GD&T Basics",def:"Precision 0.001mm tool.",ex:"Shaft 25.013mm.",sentence:"Verified shaft."},
  {id:43,word:"Gauge",phonetic:"/ɡeɪdʒ/",cat:"measurement",group:"GD&T Basics",def:"Go/No-Go check.",ex:"Go enters, No-Go doesn't.",sentence:"Plug gauge."},
  {id:44,word:"Surface Roughness",phonetic:"/ˈrʌf.nəs/",cat:"measurement",group:"GD&T Basics",def:"Ra in μm.",ex:"Ra 0.8 smooth, 3.2 machined.",sentence:"Ra 0.8μm required."},
  {id:45,word:"Metrology",phonetic:"/mɪˈtrɒl/",cat:"measurement",group:"GD&T Basics",def:"Science of measurement.",ex:"Lab with CMMs.",sentence:"New lab."},
  {id:46,word:"True Profile",phonetic:"/ˈprəʊ.faɪl/",cat:"measurement",group:"GD&T Basics",def:"Perfect shape from dimensions.",ex:"Cam from CAD.",sentence:"Compared to true profile."},
  {id:47,word:"Basic Dimension",phonetic:"/ˈbeɪ.sɪk/",cat:"measurement",group:"GD&T Basics",def:"Exact dim, NO tolerance.",ex:"⊞30⊞ = 30mm.",sentence:"Defined by basic dims."},
  {id:48,word:"Datum Target",phonetic:"/ˈtɑː.ɡɪt/",cat:"measurement",group:"GD&T Basics",def:"Contact point for rough surface.",ex:"A1, A2, A3.",sentence:"Used datum targets."},
  {id:49,word:"Feature Control Frame",phonetic:"/freɪm/",cat:"drawing",group:"GD&T Basics",def:"Box: symbol + tol + datums.",ex:"| ⊕ | ⌀0.5 | A | B |",sentence:"Read the FCF."},
  {id:50,word:"Section View",phonetic:"/ˈsek.ʃən/",cat:"drawing",group:"GD&T Basics",def:"Cut view for internals.",ex:"Section A-A.",sentence:"In section view."},
  {id:51,word:"Detail View",phonetic:"/ˈdiː.teɪl/",cat:"drawing",group:"GD&T Basics",def:"Zoomed small feature.",ex:"SCALE 5:1.",sentence:"Detail view 4:1."},
  {id:52,word:"Reference Dim",phonetic:"/ˈref.ər.əns/",cat:"drawing",group:"GD&T Basics",def:"In brackets — info only.",ex:"(100) reference.",sentence:"As reference."},
  {id:53,word:"Counterbore",phonetic:"/ˈkaʊn.tə.bɔːr/",cat:"drawing",group:"GD&T Basics",def:"Flat hole for bolt recess.",ex:"⌀20 × 10mm.",sentence:"Bolt recessed."},
  {id:54,word:"Countersink",phonetic:"/ˈkaʊn.tə.sɪŋk/",cat:"drawing",group:"GD&T Basics",def:"Cone for flush screws.",ex:"90° × ⌀18mm.",sentence:"Flush screws."},
  {id:55,word:"GD&T",phonetic:"/dʒiː diː/",cat:"drawing",group:"GD&T Basics",def:"Geometric Dimensioning & Tolerancing.",ex:"⌀0.2mm true position.",sentence:"Clear design intent."},
  {id:56,word:"Hardness",phonetic:"/ˈhɑːd.nəs/",cat:"material",group:"GD&T Basics",def:"HRC scale. Higher = harder.",ex:"28-32 medium.",sentence:"Treated to 28-32 HRC."},
  {id:57,word:"Heat Treatment",phonetic:"/hiːt/",cat:"material",group:"GD&T Basics",def:"Heating/cooling for properties.",ex:"Quenching hardens.",sentence:"After machining."},
  {id:58,word:"Surface Finish",phonetic:"/ˈfɪn.ɪʃ/",cat:"material",group:"GD&T Basics",def:"Texture as Ra.",ex:"Ra 0.4 bearing.",sentence:"Ra 1.6 grinding."},
  {id:59,word:"Chamfer",phonetic:"/ˈtʃæm.fər/",cat:"material",group:"GD&T Basics",def:"45° angled cut.",ex:"1×45° on shaft.",sentence:"Easier insertion."},
  {id:60,word:"Fillet",phonetic:"/ˈfɪl.ɪt/",cat:"material",group:"GD&T Basics",def:"Internal curve, reduces stress.",ex:"R3 at shoulder.",sentence:"R5 prevents cracking."},
]

export const categories = [
  {key:"all",label:"All",color:"#94a3b8"},
  {key:"general",label:"General",color:"#3b82f6"},
  {key:"tolerance",label:"Tolerance",color:"#ef4444"},
  {key:"datum",label:"Datum",color:"#f59e0b"},
  {key:"symbol",label:"Symbols",color:"#22c55e"},
  {key:"measurement",label:"Measure",color:"#a855f7"},
  {key:"drawing",label:"Drawing",color:"#06b6d4"},
  {key:"material",label:"Material",color:"#ec4899"},
]

export const catColor = c => categories.find(x=>x.key===c)?.color||"#94a3b8"
